name: mapa_gabinetes
description: "App para gerir dotações de gabinetes médicos"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_storage: ^13.0.5
  json_annotation: ^4.9.0
  syncfusion_flutter_calendar: ^32.1.19
  flutter_typeahead: ^5.2.0
  intl: 0.20.2
  get: ^4.6.6
  shared_preferences: ^2.2.2

# Removidas dependências de banco local para migração Firebase
#   sqflite: ^2.4.2
#   path: ^1.9.1
#   path_provider: ^2.1.5
#   sqflite_common_ffi: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/am_icon.png

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
      - asset: fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: fonts/Montserrat-Bold.ttf
        weight: 700